### ISSUE TITLE
Virtual Server Traffic - no data

### ISSUE THREAD

**Issue by mdevlinf5** [f5devcentral/application-study-tool#1]
I installed on ubuntu 22.04, graphs work for CPU, connections, and other data points, however im not able to see overall traffic on my bigip.  This applies to overall traffic on the box, as well as individual virtual servers.

**Comment by clhain** [comment]
Ok, fairly confident this is because you're using a guest account on the collector (let me know if this is not the case). There are a small number of metrics that require permissions to run bash commands (mostly some of the virtual server level  SSL/HTTP profile metrics). The following improvements will be in release 0.3.0:

- Updated README with better callout to different account permission levels and which metrics you lose with guest.
- Updated dashboard panels which leverage these metrics to include description of this requirement
- Updated collector warnings to include a note about permissions on the relevant endpoint http requests when they fail

**Comment by clhain** [comment]
https://github.com/f5devcentral/application-study-tool/releases/tag/v0.3.0 Please give it a try and re-open if that didn't fix.
